# Generated by Django 5.2.6 on 2025-09-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliated_publisher',
            field=models.ForeignKey(blank=True, help_text='Publisher this editor is affiliated with (Editor role).', limit_choices_to={'editors__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_editors', to='articles.publisher'),
        ),
    ]
