# Generated by Django 5.2.6 on 2025-09-11 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_user_affiliated_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='affiliated_publisher',
            field=models.ForeignKey(blank=True, help_text='Publisher this user is affiliated with (Editor/Journalist roles).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_users', to='articles.publisher'),
        ),
    ]
