# Generated by Django 5.2.6 on 2025-09-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_user_affiliated_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='independent_articles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='independent_newsletters',
        ),
    ]
